Repository octokit/app.js, pull requests merged in 2021-03, with the labels that each got.

#214 test: create child `tsconfig.json`
  test/tsconfig.json
Labels: maintenance

#217 feat: `createNodeMiddleware()`. Deprecates `getNodeMiddleware()`
  README.md
  package.json
  src/index.ts
  test/deprecations.test.ts
  test/smoke.test.ts
Labels: feature

#219 feat: `App.defaults(options)`
  README.md
  src/index.ts
  test/readme-examples.test.ts
  test/smoke.test.ts
Labels: feature

#221 feat(createNodeMiddleware): `log` option
  README.md
  package-lock.json
  package.json
  src/index.ts
  src/middleware/node/index.ts
  src/middleware/node/on-unhandled-request-default.ts
  src/types.ts
  src/webhooks.ts
  test/node-middleware.test.ts
  test/readme-examples.test.ts
Labels: feature

#223 feat(typescript): derive `octokit` type from `Octokit` option
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/each-installation.ts
  src/each-repository.ts
  src/index.ts
  src/middleware/node/index.ts
  src/types.ts
  test/typescript-validate.ts
Labels: feature, typescript
