Repository octokit/app.js, pull requests merged in 2021-04, with the labels that each got.

#224 fix(typescript): `app.oauth` type
  package-lock.json
  src/index.ts
  src/middleware/node/index.ts
Labels: bug, typescript

#228 ci(test): `test_matrix` and `test` jobs
  .github/workflows/test.yml
Labels: maintenance

#227 feat(typescript): Inherit types from `defaults.Octokit` set via `App.defaults({ Octokit })`
  src/index.ts
  src/types.ts
  test/typescript-validate.ts
Labels: feature, typescript

#229 fix(typescript): fix types for `octokit` instances in `app.oauth.*` APIs'
  package-lock.json
  package.json
  src/index.ts
  test/typescript-validate.ts
Labels: bug, typescript

#231 fix(deps): bump `@octokit/webhooks` to `9.0.0-beta.5`
  package-lock.json
  package.json
  test/readme-examples.test.ts
Labels: feature

#232 feat: v12
  package-lock.json
  package.json
  test/readme-examples.test.ts
Labels: blocked, feature

#235 fix: remove type imports from "http" for Deno compatibility
  package-lock.json
  package.json
  src/middleware/node/index.ts
  src/middleware/node/on-unhandled-request-default.ts
Labels: bug, deno, typescript

#237 fix(typescript): avoid `import { App } from "../...d.ts"` in types export
  src/middleware/node/index.ts
Labels: bug, deno, typescript

#241 ci: add NodeJS v16 to test matrix
  .github/workflows/test.yml
Labels: maintenance
