Repository octokit/app.js, pull requests merged in 2021-02, with the labels that each got.

#196 Fix typo in readme code example
  README.md
Labels: bug, documentation

#199 fix: update dependency @octokit/webhooks to v8. Pass unauthenticated `octokit` instance to webhook event handler in case the event payload has no `"installation"` key
  package-lock.json
  package.json
  src/webhooks.ts
  test/webhooks.test.ts
Labels: bug

#201 fix(types): add explicit return type to webhooks() function
  package-lock.json
  src/webhooks.ts
Labels: bug, typescript

#204 docs: add reference to reasoning behind the explicit return type
  src/webhooks.ts
Labels: maintenance, typescript

#206 feat(typescript): `options.oauth.allowSignup` is optional and boolean
  README.md
  src/index.ts
  src/types.ts
  test/oauth.test.ts
Labels: feature, typescript

#208 Typo in README
  README.md
Labels: bug, documentation
