Repository octokit/app.js, pull requests merged in 2022-06, with the labels that each got.

#281 Applies lint fixes to the security policy
  SECURITY.md
Labels: documentation, maintenance

#291 build(npm): replace 'pika' command with 'pika-pack'
  package.json
Labels: bug

#295 ci: adds codeql-analysis.yml for codeql execution
  .github/workflows/codeql-analysis.yml
Labels: maintenance
